language: julia
os:
  - osx
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
git:
  depth: 999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
 allow_failures:
 - julia: nightly

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
